using Classses;
using System.Reflection.Emit;

namespace BilbasenKonsol
{
        internal class Program
        {
            //100 cars that run on pertrol or diesel that have been generated by ChatGBT:
            public static List<Car> pertrol_dieselCars = new List<Car>()
                    {
                    new Car("Ford", "Mustang", 1963, "Red", 430, "Petrol", 45000),
                    new Car("Toyota", "Camry", 2020, "Blue", 200, "Petrol", 35000),
                    new Car("Chevrolet", "Corvette", 2022, "Silver", 650, "Petrol", 80000),
                    new Car("Honda", "Civic", 2015, "White", 158, "Petrol", 25000),
                    new Car("BMW", "3 Series", 2019, "Black", 320, "Diesel", 40000),
                    new Car("Audi", "A6", 2018, "Gray", 255, "Diesel", 45000),
                    new Car("Mercedes-Benz", "CLS", 2021, "Silver", 362, "Petrol", 60000),
                    new Car("Volkswagen", "Golf", 2017, "Blue", 148, "Petrol", 30000),
                    new Car("Porsche", "911", 2023, "Yellow", 450, "Petrol", 120000),
                    new Car("Ferrari", "F812", 2020, "Red", 789, "Petrol", 350000),
                    new Car("Dodge", "Charger", 2016, "Black", 292, "Petrol", 45000),
                    new Car("Subaru", "WRX", 2018, "Blue", 268, "Petrol", 35000),
                    new Car("Lexus", "RX 350", 2021, "Silver", 295, "Petrol", 50000),
                    new Car("Jeep", "Wrangler", 2022, "Green", 285, "Petrol", 55000),
                    new Car("Hyundai", "Sonata", 2019, "Gray", 180, "Petrol", 30000),
                    new Car("Nissan", "GT-R", 2022, "Black", 565, "Petrol", 100000),
                    new Car("Kia", "Optima", 2017, "White", 185, "Petrol", 28000),
                    new Car("Volvo", "XC90", 2020, "Blue", 316, "Diesel", 60000),
                    new Car("Mazda", "MX-5", 2018, "Red", 181, "Petrol", 30000),
                    new Car("Infiniti", "Q50", 2021, "Black", 300, "Diesel", 45000),
                    new Car("Jaguar", "XF", 2019, "Silver", 296, "Diesel", 50000),
                    new Car("Genesis", "G80", 2023, "Gray", 375, "Petrol", 65000),
                    new Car("Land Rover", "Discovery", 2017, "White", 254, "Diesel", 70000),
                    new Car("Buick", "Regal", 2021, "Black", 250, "Petrol", 40000),
                    new Car("Fiat", "500", 2016, "Red", 101, "Petrol", 20000),
                    new Car("Mini", "Cooper", 2020, "Yellow", 134, "Petrol", 35000),
                    new Car("Lincoln", "Navigator", 2023, "Silver", 450, "Diesel", 80000),
                    new Car("Maserati", "Ghibli", 2019, "Blue", 345, "Diesel", 90000),
                    new Car("Chrysler", "300C", 2021, "Black", 363, "Petrol", 50000),
                    new Car("Bentley", "Continental GT", 2018, "White", 626, "Petrol", 200000),
                    new Car("Aston Martin", "DB11", 2022, "Gray", 630, "Petrol", 250000),
                    new Car("Rolls-Royce", "Phantom", 2020, "Black", 563, "Diesel", 400000),
                    new Car("Bugatti", "Chiron", 2023, "Blue", 1500, "Petrol", 3000000),
                    new Car("Lamborghini", "Aventador", 2024, "Orange", 730, "Petrol", 400000),
                    new Car("Alfa Romeo", "Giulia", 2017, "Red", 276, "Diesel", 60000),
                    new Car("Subaru", "Outback", 2022, "Green", 182, "Diesel", 40000),
                    new Car("Lexus", "ES 350", 2020, "Silver", 302, "Petrol", 50000),
                    new Car("Audi", "Q7", 2021, "Gray", 335, "Diesel", 70000),
                    new Car("Mercedes-AMG", "GLC 63", 2023, "Black", 469, "Petrol", 90000),
                    new Car("Volkswagen", "Passat", 2019, "White", 174, "Diesel", 35000),
                    new Car("Porsche", "Panamera", 2020, "Blue", 325, "Diesel", 80000),
                    new Car("Jaguar", "F-Type", 2021, "Red", 444, "Petrol", 110000),
                    new Car("BMW", "X5", 2022, "Silver", 523, "Diesel", 95000),
                    new Car("Land Rover", "Range Rover", 2023, "Black", 395, "Diesel", 120000),
                    new Car("Bentley", "Flying Spur", 2019, "White", 626, "Petrol", 250000),
                    new Car("Cadillac", "CT5", 2020, "Gray", 335, "Diesel", 60000),
                    new Car("Rolls-Royce", "Cullinan", 2021, "Black", 563, "Diesel", 500000),
                    new Car("Aston Martin", "Vantage", 2018, "Blue", 503, "Petrol", 200000),
                    new Car("Ferrari", "Portofino", 2023, "Red", 612, "Petrol", 300000),
                    new Car("Lamborghini", "Huracan", 2024, "Yellow", 630, "Petrol", 350000),
                    new Car("McLaren", "570S", 2021, "Orange", 562, "Petrol", 250000),
                    new Car("Alfa Romeo", "Stelvio", 2019, "White", 276, "Diesel", 50000),
                    new Car("Buick", "Enclave", 2022, "Black", 310, "Petrol", 40000),
                    new Car("Cadillac", "Escalade", 2018, "Silver", 420, "Petrol", 80000),
                    new Car("Lincoln", "Aviator", 2021, "Blue", 400, "Diesel", 70000),
                    new Car("Genesis", "GV80", 2023, "White", 375, "Petrol", 65000),
                    new Car("Infiniti", "QX50", 2019, "Black", 268, "Diesel", 45000),
                    new Car("Kia", "Sorento", 2020, "Red", 281, "Petrol", 35000),
                    new Car("Maserati", "Levante", 2018, "Gray", 345, "Diesel", 80000),
                    new Car("Nissan", "Pathfinder", 2021, "Blue", 284, "Diesel", 50000),
                    new Car("Subaru", "Forester", 2017, "Green", 182, "Diesel", 40000),
                    new Car("Tesla", "Model X", 2024, "White", 1, "Electric", 80000),
                    new Car("Toyota", "RAV4", 2022, "Silver", 219, "Petrol", 30000),
                    new Car("Volvo", "XC60", 2019, "Black", 316, "Diesel", 55000),
                    new Car("VW", "Atlas Cross Sport", 2023, "Red", 276, "Diesel", 45000),
                    new Car("Mazda", "CX-5", 2020, "Blue", 187, "Petrol", 35000),
                    new Car("BMW", "M5", 2018, "Black", 600, "Petrol", 90000),
                    new Car("Audi", "RS7", 2022, "Gray", 591, "Petrol", 120000),
                    new Car("Mercedes-Benz", "GLE 450", 2021, "White", 362, "Petrol", 80000),
                    new Car("Land Rover", "Defender", 2020, "Green", 296, "Diesel", 75000),
                    new Car("Porsche", "Cayenne", 2023, "Black", 541, "Diesel", 90000),
                    new Car("Ford", "F-150", 2021, "Red", 400, "Petrol", 45000),
                    new Car("Chevrolet", "Silverado", 2020, "Blue", 355, "Petrol", 40000),
                    new Car("Dodge", "RAM 1500", 2019, "Black", 305, "Petrol", 50000),
                    new Car("GMC", "Sierra", 2023, "White", 420, "Petrol", 55000),
                    new Car("Toyota", "Tacoma", 2018, "Gray", 278, "Petrol", 35000),
                    new Car("Nissan", "Titan", 2022, "Silver", 400, "Petrol", 45000),
                    new Car("Honda", "Ridgeline", 2017, "Red", 280, "Petrol", 40000),
                    new Car("Jeep", "Gladiator", 2021, "Black", 285, "Petrol", 50000),
                    new Car("RAM", "2500", 2020, "Gray", 400, "Diesel", 60000),
                    new Car("Chevrolet", "Colorado", 2019, "Orange", 308, "Petrol", 40000),
                    new Car("Ford", "Ranger", 2023, "Blue", 270, "Diesel", 50000),
                    new Car("GMC", "Canyon", 2018, "White", 181, "Diesel", 45000),
                    new Car("Toyota", "Tundra", 2021, "Black", 381, "Petrol", 50000),
                    new Car("Nissan", "Frontier", 2022, "Silver", 310, "Petrol", 40000),
                    new Car("Honda", "HR-V", 2019, "Blue", 141, "Petrol", 30000),
                    new Car("Subaru", "Crosstrek", 2020, "Orange", 152, "Petrol", 35000),
                    new Car("Hyundai", "Tucson", 2023, "White", 187, "Petrol", 30000),
                    new Car("Kia", "Sportage", 2018, "Red", 181, "Diesel", 35000),
                    new Car("Mazda", "CX-3", 2021, "Black", 148, "Petrol", 32000),
                    new Car("Jeep", "Compass", 2019, "Gray", 180, "Diesel", 30000),
                    new Car("VW", "Tiguan", 2022, "Blue", 184, "Petrol", 32000),
                    new Car("Ford", "Escape", 2020, "Silver", 250, "Petrol", 35000),
                    new Car("Chevrolet", "Equinox", 2017, "Black", 170, "Diesel", 30000),
                    new Car("Dodge", "Journey", 2018, "Red", 172, "Petrol", 25000),
                    new Car("GMC", "Terrain", 2021, "White", 170, "Diesel", 30000),
                    new Car("Jeep", "Cherokee", 2024, "Gray", 271, "Petrol", 40000),
                    new Car("RAM", "1500", 2019, "Blue", 395, "Petrol", 45000),
                    new Car("Toyota", "Highlander", 2022, "Black", 295, "Petrol", 40000),
                    new Car("Honda", "Civic Type R", 2023, "Black", 306, "Petrol", 38000),
                    new Car("Ford", "Bronco", 2023, "Gray", 270, "Petrol", 35000),

                    };

            //40 electrical cars 
            public static List<Car> electricalCars = new List<Car>()
                    {
                    new Car("Tesla", "Model S", 2024, "White", 670, "Electric", 85000),
                    new Car("Tesla", "Model 3", 2025, "Blue", 221, "Electric", 40000),
                    new Car("Tesla", "Model X", 2024, "White", 1, "Electric", 95000),
                    new Car("Tesla", "Model Y", 2025, "Red", 480, "Electric", 60000),
                    new Car("Audi", "e-tron", 2022, "Silver", 355, "Electric", 65000),
                    new Car("BMW", "i3", 2023, "Blue", 170, "Electric", 45000),
                    new Car("BMW", "i4", 2022, "White", 523, "Electric", 55000),
                    new Car("BMW", "iX3", 2024, "Black", 286, "Electric", 60000),
                    new Car("BMW", "iX4", 2021, "Red", 326, "Electric", 65000),
                    new Car("BMW", "iX5", 2022, "Silver", 523, "Electric", 75000),
                    new Car("Chevrolet", "Bolt EV", 2023, "Blue", 200, "Electric", 35000),
                    new Car("Ford", "Mustang Mach-E", 2024, "Red", 480, "Electric", 55000),
                    new Car("Hyundai", "Kona Electric", 2022, "Black", 201, "Electric", 40000),
                    new Car("Jaguar", "I-Pace", 2024, "Blue", 394, "Electric", 70000),
                    new Car("Kia", "Niro EV", 2021, "Gray", 201, "Electric", 38000),
                    new Car("Nissan", "Leaf", 2022, "Green", 147, "Electric", 32000),
                    new Car("Porsche", "Taycan", 2023, "White", 469, "Electric", 100000),
                    new Car("Rivian", "R1T", 2024, "Orange", 750, "Electric", 75000),
                    new Car("Rivian", "R1S", 2024, "Blue", 750, "Electric", 75000),
                    new Car("Polestar", "2", 2023, "Gray", 300, "Electric", 60000),
                    new Car("Volkswagen", "ID.3", 2024, "Blue", 201, "Electric", 35000),
                    new Car("Volkswagen", "ID.4", 2022, "Silver", 276, "Electric", 40000),
                    new Car("Volvo", "XC40 Recharge", 2025, "Black", 402, "Electric", 65000),
                    new Car("Lucid", "Air", 2023, "White", 1080, "Electric", 80000),
                    new Car("Byton", "M-Byte", 2024, "Black", 272, "Electric", 60000),
                    new Car("Bollinger", "B2", 2024, "Yellow", 614, "Electric", 75000),
                    new Car("Lordstown", "Endurance", 2024, "Gray", 600, "Electric", 55000),
                    new Car("Lightning E-Motorcycles", "LS-218", 2023, "Red", 200, "Electric", 40000),
                    new Car("Rimac", "Nevera", 2022, "Blue", 1914, "Electric", 200000),
                    new Car("Tesla", "Roadster", 2023, "Silver", 1000, "Electric", 200000),

                    };
        // 40 Motercykles
        public static List<Car> motorCycle = new List<Car>()
                {
                new Car("Harley-Davidson", "Road King", 2023, "Black", 80, "Petrol", 20000),
                new Car("BMW", "R 1250 GS Adventure", 2024, "Blue", 136, "Petrol", 23000),
                new Car("Ducati", "Monster", 2022, "Red", 111, "Petrol", 12000),
                new Car("Yamaha", "YZF-R1M", 2023, "Blue", 200, "Petrol", 26000),
                new Car("Honda", "CBR1000RR", 2022, "Red", 214, "Petrol", 16000),
                new Car("Kawasaki", "Ninja ZX-10R", 2023, "Green", 200, "Petrol", 18000),
                new Car("Triumph", "Street Triple", 2022, "Black", 121, "Petrol", 11000),
                new Car("Suzuki", "GSX-R1000R", 2023, "Yellow", 199, "Petrol", 17000),
                new Car("Aprilia", "RSV4 RF", 2024, "Silver", 201, "Petrol", 21000),
                new Car("Indian", "Chieftain Dark Horse", 2023, "Black", 122, "Petrol", 25000),
                new Car("KTM", "1290 Super Duke R", 2022, "Orange", 177, "Petrol", 19000),
                new Car("Harley-Davidson", "Iron 883", 2023, "Black", 50, "Petrol", 10000),
                new Car("BMW", "R nineT", 2024, "White", 109, "Petrol", 15000),
                new Car("Ducati", "Panigale V4", 2022, "Red", 214, "Petrol", 25000),
                new Car("Yamaha", "MT-09", 2023, "Black", 115, "Petrol", 9000),
                new Car("Honda", "CRF450R", 2022, "Red", 60, "Petrol", 9000),
                new Car("Kawasaki", "KX450", 2023, "Green", 56, "Petrol", 8000),
                new Car("Triumph", "Bonneville T100", 2022, "Black", 55, "Petrol", 11000),
                new Car("Suzuki", "DR-Z400S", 2023, "Yellow", 39, "Petrol", 7000),
                new Car("Aprilia", "Tuono V4 Factory", 2024, "Silver", 175, "Petrol", 19000),
                new Car("Indian", "Scout Bobber", 2023, "Black", 100, "Petrol", 12000),
                new Car("KTM", "690 Enduro R", 2022, "Orange", 74, "Petrol", 11000),
                new Car("Harley-Davidson", "Sportster Iron 883", 2023, "Black", 51, "Petrol", 9500),
                new Car("BMW", "S 1000 RR", 2024, "Blue", 207, "Petrol", 18000),
                new Car("Ducati", "Diavel 1260 S", 2022, "Red", 162, "Petrol", 22000),
                new Car("Yamaha", "MT-07", 2023, "Blue", 73, "Petrol", 8000),
                new Car("Honda", "Africa Twin", 2022, "Red", 94, "Petrol", 14000),
                new Car("Kawasaki", "Versys 1000 SE LT+", 2023, "Green", 118, "Petrol", 15000),
                new Car("Triumph", "Rocket 3", 2022, "Black", 165, "Petrol", 22000),
                new Car("Suzuki", "Hayabusa", 2023, "Silver", 188, "Petrol", 18000),
                new Car("Aprilia", "RS 660", 2024, "Grey", 100, "Petrol", 12000),
                new Car("Indian", "FTR 1200", 2023, "Red", 120, "Petrol", 13000),
                new Car("KTM", "390 Adventure", 2022, "Orange", 44, "Petrol", 7000),
                new Car("Harley-Davidson", "Fat Boy", 2023, "Black", 65, "Petrol", 14000),
                new Car("BMW", "G 310 R", 2024, "White", 34, "Petrol", 5000),
                new Car("Ducati", "Multistrada V4", 2022, "Red", 168, "Petrol", 24000),
                new Car("Yamaha", "YZ450F", 2023, "Blue", 60, "Petrol", 9000),
                new Car("Honda", "Rebel 1100", 2022, "Red", 87, "Petrol", 10000),
                new Car("Kawasaki", "Z900", 2023, "Green", 123, "Petrol", 11000),
                new Car("Triumph", "Tiger 900", 2022, "Black", 94, "Petrol", 13000),
                new Car("Suzuki", "SV650X", 2023, "Yellow", 75, "Petrol", 8000),
                new Car("Aprilia", "RS 125", 2024, "Silver", 28, "Petrol", 5000),
                new Car("Indian", "Chief Dark Horse", 2023, "Black", 89, "Petrol", 12000),
                new Car("KTM", "200 Duke", 2022, "Orange", 25, "Petrol", 4000),

                };
                
        public static void Main()
            {
                Label:
                Console.Clear();
                Console.WriteLine("Which cars would you like to search in \n1. Petrol and Diesel cars\n2. Electrical cars \n3. Motorcycles");
                string choice = Console.ReadLine();
                switch (choice)
                    {
                        case "1":
                            SearchMenu(pertrol_dieselCars);
                            break;

                        case "2":
                            SearchMenu(electricalCars);
                            break;

                        case "3":
                        SearchMenu(motorCycle);
                        break;

                    }
            }
        public static void SearchMenu(List<Car> list)
            {
                Console.WriteLine("Which menu do you want to use?\n1. Show all cars with the same brand as the first car in the database.\n2. Show all cars with 200 or more HK.\n3. Show all red cars.");
                Console.WriteLine("4. Show amount of cars with the same brand as the first car in the database.\n5. Show cars from 1980 - 1999.");
                string choice = Console.ReadLine();
                switch (choice)
                {
                    case "1":
                        FirstBrandInDatabase(list);
                        Console.WriteLine("Press Enter to continue.");
                        Console.Read();
                        break;
                    case "2":
                        MoreThen200HK(list);
                        Console.WriteLine("Press Enter to continue.");
                        Console.Read();
                        break;
                    case "3":
                        RedCars(list);
                        Console.WriteLine("Press Enter to continue.");
                        Console.Read();
                        break;
                    case "4":
                        AmountOfCarsWithTheFirstBrandInTheDatabase(list);
                        Console.WriteLine("Press Enter to continue.");
                        Console.Read();
                        break;
                    case "5":
                        CarsFrom80_99(list);
                        Console.WriteLine("Press Enter to continue.");
                        Console.Read();
                        break;
                    default:
                        Main();
                        break;
                }
            }
        public static void FirstBrandInDatabase(List<Car> list)
            {
                Console.WriteLine($"\nCars matching the Brand 'Ford':");
                foreach (Car car in list)
                {
                    if (car.Brand == "Ford")
                    {
                    Console.WriteLine($"Brand: {car.Brand}. Model: {car.Model}. Year: {car.Year}. Color: {car.Color}. HorsePower: {car.HorsePower}. Number of cylinders: {car.FuelType}. \n");
                    }
                }
            }
        public static void MoreThen200HK(List<Car> list)
            {
                Console.WriteLine("\nCars with more then 200 HK:");
                foreach (Car car in list)
                {
                    if (car.HorsePower >= 200)
                    {
                    Console.WriteLine($"Brand: {car.Brand}. Model: {car.Model}. Year: {car.Year}. Color: {car.Color}. HorsePower: {car.HorsePower}. Number of cylinders: {car.FuelType}.\n");
                    }
                }
            }
        public static void RedCars(List<Car> list)
            {
                Console.WriteLine("\nCars that are red:");
                foreach (Car car in list)
                {
                    if (car.Color == "Red")
                    {
                    Console.WriteLine($"Brand: {car.Brand}. Model: {car.Model}. Year: {car.Year}. Color: {car.Color}. HorsePower: {car.HorsePower}. Number of cylinders: {car.FuelType}.\n");
                    }
                }
            }
        public static void AmountOfCarsWithTheFirstBrandInTheDatabase(List<Car> list)
            {
                int carAmount = 0;
                foreach (Car car in list)
                {
                    if (car.Brand == "Ford")
                    {
                    carAmount++;
                    }
                }
                    Console.WriteLine($"Amount of cars of the brand 'Ford': {carAmount}.\n");
            }
        public static void CarsFrom80_99(List<Car> list)
            {
                Console.WriteLine("Cars from 1980 - 1999.");
                foreach (Car car in list)
                {
                    if (car.Year >= 1980 && car.Year <= 1999)
                {
                    Console.WriteLine($"Brand: {car.Brand}. Model: {car.Model}. Year: {car.Year}. Color: {car.Color}. HorsePower: {car.HorsePower}. Number of cylinders: {car.FuelType}.\n");
                }
            }
        }
    }
}

 //OPGAVE PROGRAM:
//Mandag:
//Start med opbevaring af mindst 100 biler
// 1. Udskriv alle biler som deler mærke med den første bil i jeres datasæt 
// 2. udskrive alle biler som har over 200HK.
// 3. Udskriv alle røde biler
// 4. Udskriv alle biler som er melle årgang 1980 og 1999

//Tirsdag:
//Tjek jeres klasse igennem, er der noget som burde ændres ud fra abstraktions-pensummet? er jeres model for kompleks?
//udvid jeres program til at have 2 klasser, en for benzin/diesel biler og en for elbiler.
//Når i har set klassen igennem og er tilfredse skal i udvide med et interface 
//Interfaces skal gøre at alle bil-klassser skal have en pris, model og mærke 

//Onsdag:
//Nu skal alle jeres attributter være private, hvis de ikke allerede er det. Virker jeres program stadig? Hvis ikke skal i definere Get og Set metoder, så det virker igen!
//Bagefter kan i begynde at diagrammere jeres UML Diagram 

//Torsdag:
//Jeres bilsægler side, vil nu gerne udvide til både at have benzin/diesel biler, elbiler og motercykler, 
//De skal bruge en klasse hver og i skal lave en klasse som de alle sammen arver fra.
//I bestemmmer selv, om det er en abstrakt klasse eller bare en normal klasse som de andre arver.
//her er det vigtigt at bruge konceptere fra abstraktion og overveje, hvad der skal i hver klasse!

//Fredag: 
//Igen opgaver til polymorfi - vi sætter fokus på jeres projekt og i for muligheden for at opbygge eller arbejde videre med klasserne til det lange selvvalgte projekt.